apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lyre.fullname" . }}-config
  labels:
    {{- include "lyre.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.web.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.embeddedTurn.enabled }}
  {{- range $key, $value := .Values.embeddedTurn.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
