/* eslint-disable */
// lyre v0.1.0 024f0a2d0af2ace2f845fcb59b0de3647daa0de4
// --
// Code generated by Webrpc-gen@v0.36.0 with typescript generator. DO NOT EDIT.
//
// webrpc-gen -schema=../proto/lyre.ridl -target=typescript -client -out=./src/lib/lyre.gen.ts

// Webrpc description and code-gen version
export const WebrpcVersion = "v1"

// Schema version of your RIDL schema
export const WebrpcSchemaVersion = "v0.1.0"

// Schema hash generated from your RIDL schema
export const WebrpcSchemaHash = "024f0a2d0af2ace2f845fcb59b0de3647daa0de4"

//
// Client interface
//

export interface LyreClient {
  /**
   * Documents GET /api/rooms/{room_id}; REST fetch remains the runtime transport in this increment.
   */
  getRoom(req: GetRoomRequest, headers?: object, signal?: AbortSignal): Promise<GetRoomResponse>

  /**
   * Documents POST /api/rooms/{room_id}/join; REST fetch remains the runtime transport in this increment.
   */
  joinRoom(req: JoinRoomRequest, headers?: object, signal?: AbortSignal): Promise<JoinRoomResponse>

  /**
   * Documents POST /api/rooms/{room_id}/leave; REST fetch remains the runtime transport in this increment.
   */
  leaveRoom(req: LeaveRoomRequest, headers?: object, signal?: AbortSignal): Promise<LeaveRoomResponse>

  /**
   * Documents GET /api/noise/providers; REST fetch remains the runtime transport in this increment.
   */
  getNoiseProviders(headers?: object, signal?: AbortSignal): Promise<GetNoiseProvidersResponse>

  /**
   * Documents GET /api/webrtc/ice-servers; REST fetch remains the runtime transport in this increment.
   */
  getIceServers(headers?: object, signal?: AbortSignal): Promise<GetIceServersResponse>

  /**
   * Documents GET /api/webrtc/topology; REST fetch remains the runtime transport in this increment.
   */
  getMediaTopology(headers?: object, signal?: AbortSignal): Promise<GetMediaTopologyResponse>

  /**
   * Documents GET /api/rooms/{room_id}/media-relay; REST fetch remains the runtime transport in this increment.
   */
  getMediaRelay(req: GetMediaRelayRequest, headers?: object, signal?: AbortSignal): Promise<GetMediaRelayResponse>

  /**
   * Documents POST /api/rooms/{room_id}/media-relay/start; REST fetch remains the runtime transport in this increment.
   */
  startMediaRelay(req: StartMediaRelayRequest, headers?: object, signal?: AbortSignal): Promise<StartMediaRelayResponse>

  /**
   * Documents POST /api/rooms/{room_id}/media-relay/stop; REST fetch remains the runtime transport in this increment.
   */
  stopMediaRelay(req: StopMediaRelayRequest, headers?: object, signal?: AbortSignal): Promise<StopMediaRelayResponse>

  /**
   * Documents POST /api/rooms/{room_id}/media-relay/tracks; REST fetch remains the runtime transport in this increment.
   */
  registerMediaTrack(req: RegisterMediaTrackRequest, headers?: object, signal?: AbortSignal): Promise<RegisterMediaTrackResponse>

  /**
   * Documents POST /api/rooms/{room_id}/server-media/offer; REST fetch remains the runtime transport in this increment.
   */
  answerServerMediaOffer(req: AnswerServerMediaOfferRequest, headers?: object, signal?: AbortSignal): Promise<AnswerServerMediaOfferResponse>

  /**
   * Documents POST /api/rooms/{room_id}/server-media/candidates; REST fetch remains the runtime transport in this increment.
   */
  addServerMediaIceCandidate(req: AddServerMediaIceCandidateRequest, headers?: object, signal?: AbortSignal): Promise<AddServerMediaIceCandidateResponse>

  /**
   * Documents GET /api/rooms/{room_id}/server-media/candidates?user_id={userID}; REST fetch remains the runtime transport in this increment.
   */
  getServerMediaIceCandidates(req: GetServerMediaIceCandidatesRequest, headers?: object, signal?: AbortSignal): Promise<GetServerMediaIceCandidatesResponse>
}


//
// Schema types
//

export enum NoiseProvider {
  OFF = 'OFF',
  RNNOISE = 'RNNOISE',
  DEEPFILTERNET = 'DEEPFILTERNET'
}

export enum MediaTopologyMode {
  P2P_MESH = 'P2P_MESH',
  MEDIA_RELAY = 'MEDIA_RELAY'
}

export enum MediaRelayStatus {
  INACTIVE = 'INACTIVE',
  ACTIVE = 'ACTIVE'
}

export enum MediaRelayMode {
  P2P_MESH = 'P2P_MESH',
  MEDIA_RELAY = 'MEDIA_RELAY'
}

export enum MediaTrackKind {
  AUDIO = 'AUDIO',
  VIDEO = 'VIDEO'
}

export enum ServerMediaSessionState {
  NEW = 'NEW',
  NEGOTIATING = 'NEGOTIATING',
  CONNECTED = 'CONNECTED',
  CLOSED = 'CLOSED'
}

export interface NoiseCancellationConfig {
  provider: NoiseProvider
  intensity: number
  voiceActivityThreshold: number
}

export interface IceServerConfig {
  urls: Array<string>
  username?: string
  credential?: string
}

export interface MediaTopology {
  mode: MediaTopologyMode
  turnRelaySupported: boolean
  serverSideAudioProcessing: boolean
  serverSideNoiseCancelling: boolean
  serverNoiseCancellingRequires: MediaTopologyMode
}

export interface MediaRelayTrack {
  trackID: string
  kind: MediaTrackKind
}

export interface MediaRelayParticipant {
  userID: string
  tracks: Array<MediaRelayTrack>
}

export interface MediaRelayRoomStatus {
  roomID: string
  status: MediaRelayStatus
  mode: MediaRelayMode
  serverSideAudioProcessing: boolean
  serverSideNoiseCancelling: boolean
  noise: NoiseCancellationConfig
  participants: Array<MediaRelayParticipant>
}

export interface JoinRoomInput {
  nickname?: string
  noise?: NoiseCancellationConfig
}

export interface StartMediaRelayInput {
  noise?: NoiseCancellationConfig
}

export interface StopMediaRelayInput {
  userID: string
}

export interface RegisterMediaTrackInput {
  userID: string
  trackID: string
  kind: MediaTrackKind
}

export interface ServerMediaOfferInput {
  userID: string
  audioTrackID: string
  sdp: string
}

export interface ServerMediaAnswer {
  roomID: string
  userID: string
  audioTrackID: string
  sdp: string
  state: ServerMediaSessionState
}

export interface ServerMediaIceCandidate {
  roomID: string
  userID: string
  candidate: string
  sdpMid?: string
  sdpMLineIndex?: number
  usernameFragment?: string
}

export interface UserProfile {
  id: string
  nickname: string
  joinedAt: string
  noise: NoiseCancellationConfig
}

export interface RoomSnapshot {
  roomID: string
  users: Array<UserProfile>
}

export interface JoinRoomResponse {
  user: UserProfile
  room: RoomSnapshot
}

export interface GetRoomRequest {
  roomID: string
}

export interface GetRoomResponse {
  room: RoomSnapshot
}

export interface JoinRoomRequest {
  roomID: string
  nickname?: string
  noise?: NoiseCancellationConfig
}

export interface JoinRoomResponse {
  user: UserProfile
  room: RoomSnapshot
}

export interface LeaveRoomRequest {
  roomID: string
  userID: string
}

export interface LeaveRoomResponse {
  room: RoomSnapshot
}

export interface GetNoiseProvidersRequest {
}

export interface GetNoiseProvidersResponse {
  providers: Array<NoiseCancellationConfig>
}

export interface GetIceServersRequest {
}

export interface GetIceServersResponse {
  iceServers: Array<IceServerConfig>
}

export interface GetMediaTopologyRequest {
}

export interface GetMediaTopologyResponse {
  topology: MediaTopology
}

export interface GetMediaRelayRequest {
  roomID: string
}

export interface GetMediaRelayResponse {
  mediaRelay: MediaRelayRoomStatus
}

export interface StartMediaRelayRequest {
  roomID: string
  noise?: NoiseCancellationConfig
}

export interface StartMediaRelayResponse {
  mediaRelay: MediaRelayRoomStatus
}

export interface StopMediaRelayRequest {
  roomID: string
  userID: string
}

export interface StopMediaRelayResponse {
  mediaRelay: MediaRelayRoomStatus
}

export interface RegisterMediaTrackRequest {
  roomID: string
  userID: string
  trackID: string
  kind: MediaTrackKind
}

export interface RegisterMediaTrackResponse {
  mediaRelay: MediaRelayRoomStatus
}

export interface AnswerServerMediaOfferRequest {
  roomID: string
  userID: string
  audioTrackID: string
  sdp: string
}

export interface AnswerServerMediaOfferResponse {
  answer: ServerMediaAnswer
}

export interface AddServerMediaIceCandidateRequest {
  roomID: string
  userID: string
  candidate: string
  sdpMid?: string
  sdpMLineIndex?: number
  usernameFragment?: string
}

export interface AddServerMediaIceCandidateResponse {
  accepted: ServerMediaIceCandidate
}

export interface GetServerMediaIceCandidatesRequest {
  roomID: string
  userID: string
}

export interface GetServerMediaIceCandidatesResponse {
  candidates: Array<ServerMediaIceCandidate>
}



//
// Client
//

export class Lyre implements LyreClient {
  protected hostname: string
  protected fetch: Fetch
  protected path = '/rpc/Lyre/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname.replace(/\/*$/, '')
    this.fetch = (input: RequestInfo, init?: RequestInit) => fetch(input, init)
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  queryKey = {
    getRoom: (req: GetRoomRequest) => ['Lyre', 'getRoom', req] as const,
    joinRoom: (req: JoinRoomRequest) => ['Lyre', 'joinRoom', req] as const,
    leaveRoom: (req: LeaveRoomRequest) => ['Lyre', 'leaveRoom', req] as const,
    getNoiseProviders: () => ['Lyre', 'getNoiseProviders'] as const,
    getIceServers: () => ['Lyre', 'getIceServers'] as const,
    getMediaTopology: () => ['Lyre', 'getMediaTopology'] as const,
    getMediaRelay: (req: GetMediaRelayRequest) => ['Lyre', 'getMediaRelay', req] as const,
    startMediaRelay: (req: StartMediaRelayRequest) => ['Lyre', 'startMediaRelay', req] as const,
    stopMediaRelay: (req: StopMediaRelayRequest) => ['Lyre', 'stopMediaRelay', req] as const,
    registerMediaTrack: (req: RegisterMediaTrackRequest) => ['Lyre', 'registerMediaTrack', req] as const,
    answerServerMediaOffer: (req: AnswerServerMediaOfferRequest) => ['Lyre', 'answerServerMediaOffer', req] as const,
    addServerMediaIceCandidate: (req: AddServerMediaIceCandidateRequest) => ['Lyre', 'addServerMediaIceCandidate', req] as const,
    getServerMediaIceCandidates: (req: GetServerMediaIceCandidatesRequest) => ['Lyre', 'getServerMediaIceCandidates', req] as const,
  }

  getRoom = (req: GetRoomRequest, headers?: object, signal?: AbortSignal): Promise<GetRoomResponse> => {
    return this.fetch(
      this.url('GetRoom'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<GetRoomResponse>(_data, 'GetRoomResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  joinRoom = (req: JoinRoomRequest, headers?: object, signal?: AbortSignal): Promise<JoinRoomResponse> => {
    return this.fetch(
      this.url('JoinRoom'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<JoinRoomResponse>(_data, 'JoinRoomResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  leaveRoom = (req: LeaveRoomRequest, headers?: object, signal?: AbortSignal): Promise<LeaveRoomResponse> => {
    return this.fetch(
      this.url('LeaveRoom'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<LeaveRoomResponse>(_data, 'LeaveRoomResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  getNoiseProviders = (headers?: object, signal?: AbortSignal): Promise<GetNoiseProvidersResponse> => {
    return this.fetch(
      this.url('GetNoiseProviders'),
      createHttpRequest('{}', headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<GetNoiseProvidersResponse>(_data, 'GetNoiseProvidersResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  getIceServers = (headers?: object, signal?: AbortSignal): Promise<GetIceServersResponse> => {
    return this.fetch(
      this.url('GetIceServers'),
      createHttpRequest('{}', headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<GetIceServersResponse>(_data, 'GetIceServersResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  getMediaTopology = (headers?: object, signal?: AbortSignal): Promise<GetMediaTopologyResponse> => {
    return this.fetch(
      this.url('GetMediaTopology'),
      createHttpRequest('{}', headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<GetMediaTopologyResponse>(_data, 'GetMediaTopologyResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  getMediaRelay = (req: GetMediaRelayRequest, headers?: object, signal?: AbortSignal): Promise<GetMediaRelayResponse> => {
    return this.fetch(
      this.url('GetMediaRelay'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<GetMediaRelayResponse>(_data, 'GetMediaRelayResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  startMediaRelay = (req: StartMediaRelayRequest, headers?: object, signal?: AbortSignal): Promise<StartMediaRelayResponse> => {
    return this.fetch(
      this.url('StartMediaRelay'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<StartMediaRelayResponse>(_data, 'StartMediaRelayResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  stopMediaRelay = (req: StopMediaRelayRequest, headers?: object, signal?: AbortSignal): Promise<StopMediaRelayResponse> => {
    return this.fetch(
      this.url('StopMediaRelay'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<StopMediaRelayResponse>(_data, 'StopMediaRelayResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  registerMediaTrack = (req: RegisterMediaTrackRequest, headers?: object, signal?: AbortSignal): Promise<RegisterMediaTrackResponse> => {
    return this.fetch(
      this.url('RegisterMediaTrack'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<RegisterMediaTrackResponse>(_data, 'RegisterMediaTrackResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  answerServerMediaOffer = (req: AnswerServerMediaOfferRequest, headers?: object, signal?: AbortSignal): Promise<AnswerServerMediaOfferResponse> => {
    return this.fetch(
      this.url('AnswerServerMediaOffer'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<AnswerServerMediaOfferResponse>(_data, 'AnswerServerMediaOfferResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  addServerMediaIceCandidate = (req: AddServerMediaIceCandidateRequest, headers?: object, signal?: AbortSignal): Promise<AddServerMediaIceCandidateResponse> => {
    return this.fetch(
      this.url('AddServerMediaIceCandidate'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<AddServerMediaIceCandidateResponse>(_data, 'AddServerMediaIceCandidateResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  getServerMediaIceCandidates = (req: GetServerMediaIceCandidatesRequest, headers?: object, signal?: AbortSignal): Promise<GetServerMediaIceCandidatesResponse> => {
    return this.fetch(
      this.url('GetServerMediaIceCandidates'),
      createHttpRequest(JsonEncode(req), headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<GetServerMediaIceCandidatesResponse>(_data, 'GetServerMediaIceCandidatesResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

}

const createHttpRequest = (body: string = '{}', headers: object = {}, signal: AbortSignal | null = null): object => {
  const reqHeaders: { [key: string]: string } = { ...headers, 'Content-Type': 'application/json', [WebrpcHeader]: WebrpcHeaderValue }
  return { method: 'POST', headers: reqHeaders, body, signal }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(error) {
      throw WebrpcBadResponseError.new({
        status: res.status,
        cause: `JSON.parse(): ${error instanceof Error ? error.message : String(error)}: response text: ${text}`},
      )
    }
    if (!res.ok) {
      const code: number = (typeof data.code === 'number') ? data.code : 0
      throw (webrpcErrorByCode[code] || WebrpcError).new(data)
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>






export const JsonEncode = <T = any>(obj: T): string => {
  return JSON.stringify(obj)
}

export const JsonDecode = <T = any>(data: string | any, _typ: string = ''): T => {
  let parsed: any = data
  if (typeof data === 'string') {
    try { parsed = JSON.parse(data) } catch (err) {
      throw WebrpcBadResponseError.new({ cause: `JsonDecode: JSON.parse failed: ${(err as Error).message}` })
    }
  }
  return parsed as T
}


//
// Errors
//

type WebrpcErrorParams = { name?: string, code?: number, message?: string, status?: number, cause?: string }

export class WebrpcError extends Error {
  code: number
  status: number

  constructor(error: WebrpcErrorParams = {}) {
    super(error.message)
    this.name = error.name || 'WebrpcEndpointError'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcError.prototype)
  }

  static new(payload: any): WebrpcError {
    return new this({ message: payload.message, code: payload.code, status: payload.status, cause: payload.cause })
  }
}


export class WebrpcEndpointError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcEndpoint'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcEndpointError.prototype)
  }
}

export class WebrpcRequestFailedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcRequestFailed'
    this.code = typeof error.code === 'number' ? error.code : -1
    this.message = error.message || `request failed`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcRequestFailedError.prototype)
  }
}

export class WebrpcBadRouteError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRoute'
    this.code = typeof error.code === 'number' ? error.code : -2
    this.message = error.message || `bad route`
    this.status = typeof error.status === 'number' ? error.status : 404
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRouteError.prototype)
  }
}

export class WebrpcBadMethodError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadMethod'
    this.code = typeof error.code === 'number' ? error.code : -3
    this.message = error.message || `bad method`
    this.status = typeof error.status === 'number' ? error.status : 405
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadMethodError.prototype)
  }
}

export class WebrpcBadRequestError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRequest'
    this.code = typeof error.code === 'number' ? error.code : -4
    this.message = error.message || `bad request`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRequestError.prototype)
  }
}

export class WebrpcBadResponseError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadResponse'
    this.code = typeof error.code === 'number' ? error.code : -5
    this.message = error.message || `bad response`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadResponseError.prototype)
  }
}

export class WebrpcServerPanicError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcServerPanic'
    this.code = typeof error.code === 'number' ? error.code : -6
    this.message = error.message || `server panic`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcServerPanicError.prototype)
  }
}

export class WebrpcInternalErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcInternalError'
    this.code = typeof error.code === 'number' ? error.code : -7
    this.message = error.message || `internal error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcInternalErrorError.prototype)
  }
}

export class WebrpcClientAbortedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcClientAborted'
    this.code = typeof error.code === 'number' ? error.code : -8
    this.message = error.message || `request aborted by client`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcClientAbortedError.prototype)
  }
}

export class WebrpcStreamLostError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamLost'
    this.code = typeof error.code === 'number' ? error.code : -9
    this.message = error.message || `stream lost`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamLostError.prototype)
  }
}

export class WebrpcStreamFinishedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamFinished'
    this.code = typeof error.code === 'number' ? error.code : -10
    this.message = error.message || `stream finished`
    this.status = typeof error.status === 'number' ? error.status : 200
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamFinishedError.prototype)
  }
}


//
// Schema errors
//


export enum errors {
  WebrpcEndpoint = 'WebrpcEndpoint',
  WebrpcRequestFailed = 'WebrpcRequestFailed',
  WebrpcBadRoute = 'WebrpcBadRoute',
  WebrpcBadMethod = 'WebrpcBadMethod',
  WebrpcBadRequest = 'WebrpcBadRequest',
  WebrpcBadResponse = 'WebrpcBadResponse',
  WebrpcServerPanic = 'WebrpcServerPanic',
  WebrpcInternalError = 'WebrpcInternalError',
  WebrpcClientAborted = 'WebrpcClientAborted',
  WebrpcStreamLost = 'WebrpcStreamLost',
  WebrpcStreamFinished = 'WebrpcStreamFinished',
}

export enum WebrpcErrorCodes {
  WebrpcEndpoint = 0,
  WebrpcRequestFailed = -1,
  WebrpcBadRoute = -2,
  WebrpcBadMethod = -3,
  WebrpcBadRequest = -4,
  WebrpcBadResponse = -5,
  WebrpcServerPanic = -6,
  WebrpcInternalError = -7,
  WebrpcClientAborted = -8,
  WebrpcStreamLost = -9,
  WebrpcStreamFinished = -10,
}

export const webrpcErrorByCode: { [code: number]: any } = {
  [0]: WebrpcEndpointError,
  [-1]: WebrpcRequestFailedError,
  [-2]: WebrpcBadRouteError,
  [-3]: WebrpcBadMethodError,
  [-4]: WebrpcBadRequestError,
  [-5]: WebrpcBadResponseError,
  [-6]: WebrpcServerPanicError,
  [-7]: WebrpcInternalErrorError,
  [-8]: WebrpcClientAbortedError,
  [-9]: WebrpcStreamLostError,
  [-10]: WebrpcStreamFinishedError,
}



//
// Webrpc
//

export const WebrpcHeader = "Webrpc"

export const WebrpcHeaderValue = "webrpc@v0.36.0;gen-typescript@v0.25.0;lyre@v0.1.0"

type WebrpcGenVersions = {
  WebrpcGenVersion: string;
  codeGenName: string;
  codeGenVersion: string;
  schemaName: string;
  schemaVersion: string;
};

export function VersionFromHeader(headers: Headers): WebrpcGenVersions {
  const headerValue = headers.get(WebrpcHeader)
  if (!headerValue) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  return parseWebrpcGenVersions(headerValue)
}

function parseWebrpcGenVersions(header: string): WebrpcGenVersions {
  const versions = header.split(";")
  if (versions.length < 3) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  const [_, WebrpcGenVersion] = versions[0]!.split("@")
  const [codeGenName, codeGenVersion] = versions[1]!.split("@")
  const [schemaName, schemaVersion] = versions[2]!.split("@")

  return {
    WebrpcGenVersion: WebrpcGenVersion ?? "",
    codeGenName: codeGenName ?? "",
    codeGenVersion: codeGenVersion ?? "",
    schemaName: schemaName ?? "",
    schemaVersion: schemaVersion ?? "",
  };
}

