name: CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

env:
  NIX_CONFIG: |
    allow-import-from-derivation = true

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: NixOS/nix-installer-action@main
      - uses: Mic92/hestia@v1
      - name: Nix flake check
        run: nix flake check
      - name: Build API package
        run: nix build .#lyre-api
      - name: Check noise wasm
        run: nix develop --command cargo check -p lyre-noise-wasm --target wasm32-unknown-unknown
      - name: Clippy
        run: nix develop --command cargo clippy --workspace --all-targets -- --deny warnings
      - name: Rustfmt
        run: nix develop --command cargo fmt --check
